In [1]:
import pandas as pd

data={
    "name":["A","B"],
    "age":[25,30]
    }

df=pd.DataFrame(data)
print(df)

  name  age
0    A   25
1    B   30

In [2]:
import pandas as pd
data={
    "name":["Anu","Ammu","bannu"],
    "age":[30,40,50]
    }
df=pd.DataFrame(data)
print(df)

    name  age
0    Anu   30
1   Ammu   40
2  bannu   50

In [3]:
data = pd.read_csv('students_dataset.csv')
print(data.head())

  Region  ClassGrade Gender  Ageyears Height_cm Travel_to_School  \
0     WI          12   Male       NaN       193              Car
1     WI          12   Male       NaN       193              Car
2     WI           8   Male      14.0       174          Bicycle
3     CA          12   Male      17.0        62              Car
4     IN          12   Male      17.0       179              Bus

   Travel_time_to_School Favourite_physical_activity Allergies Vegetarian  \
0                   15.0                       Other       Yes         No
1                   15.0                       Other       Yes         No
2                    8.0           Baseball/Softball       Yes         No
3                    8.0                      Soccer        No         No
4                   20.0                   Athletics        No         No

  Favorite_School_Subject Sleep_Hours_Schoolnight Sleep_Hours_Non_Schoolnight  \
0                 Science                       6                           9
1                 Science                       6                           9
2      Physical education                       7                           9
3                   Other                       8                          10
4          Social studies                       6                           9

   Outdoor_Activities_Hours  Computer_Use_Hours  Watching_TV_Hours  \
0                      10.0                 3.0                5.0
1                      10.0                 3.0                5.0
2                      12.0                 4.0                6.0
3                      15.0                 3.0                0.0
4                       1.0                 3.0                2.0

  Work_At_Home_Hours
0                  2
1                  2
2                  3
3                 20
4                  5

In [4]:


pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
display(data.head())

,Region,ClassGrade,Gender,Ageyears,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
0,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
1,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
2,WI,8,Male,14.0,174,Bicycle,8.0,Baseball/Softball,Yes,No,Physical education,7,9,12.0,4.0,6.0,3
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5

In [5]:
new_data= data.dropna()
print(new_data)

    Region  ClassGrade  Gender  Ageyears Height_cm Travel_to_School  \
2       WI           8    Male      14.0       174          Bicycle
3       CA          12    Male      17.0        62              Car
4       IN          12    Male      17.0       179              Bus
6       MN          11    Male      16.0       175              Bus
8       NC          11  Female      16.0       175              Bus
..     ...         ...     ...       ...       ...              ...
494     AZ          12  Female      17.0       158              Bus
495     IN          10    Male      15.0     172.7              Bus
496     MD           6  Female      12.0       145              Bus
497     OH          12    Male      17.0       183              Car
498     MI          11  Female      16.0       169              Car

     Travel_time_to_School Favourite_physical_activity Allergies Vegetarian  \
2                      8.0           Baseball/Softball       Yes         No
3                      8.0                      Soccer        No         No
4                     20.0                   Athletics        No         No
6                     45.0                       Other        No         No
8                     10.0                     Cycling       Yes         No
..                     ...                         ...       ...        ...
494                   45.0                     Dancing       Yes         No
495                   15.0                     Cycling        No         No
496                   15.0                     Dancing       Yes         No
497                   15.0                Table Tennis        No         No
498                    5.0                      Rowing       Yes         No

        Favorite_School_Subject Sleep_Hours_Schoolnight  \
2            Physical education                       7
3                         Other                       8
4                Social studies                       6
6                         Other                     5.5
8    Mathematics and statistics                       8
..                          ...                     ...
494                     Science                      10
495                     Science                       9
496              Social studies                       9
497                   Languages                       4
498                     Science                       6

    Sleep_Hours_Non_Schoolnight  Outdoor_Activities_Hours  Computer_Use_Hours  \
2                             9                      12.0                 4.0
3                            10                      15.0                 3.0
4                             9                       1.0                 3.0
6                           6.5                       7.0                 1.0
8                             9                       3.0                 8.0
..                          ...                       ...                 ...
494                          13                       3.0                 0.0
495                          10                      14.0                14.0
496                          10                      14.0                 9.0
497                          10                       0.0                56.0
498                           9                       5.0                15.0

     Watching_TV_Hours Work_At_Home_Hours
2                  6.0                  3
3                  0.0                 20
4                  2.0                  5
6                 20.0                  3
8                  4.0                  7
..                 ...                ...
494                4.0                  0
495                1.0                  2
496                4.0                  3
497                0.0                 15
498               20.0                 10

[379 rows x 17 columns]

In [6]:
data.shape

(501, 17)

In [7]:
data.columns

Index(['Region', 'ClassGrade', 'Gender', 'Ageyears', 'Height_cm',
       'Travel_to_School', 'Travel_time_to_School',
       'Favourite_physical_activity', 'Allergies', 'Vegetarian',
       'Favorite_School_Subject', 'Sleep_Hours_Schoolnight',
       'Sleep_Hours_Non_Schoolnight', 'Outdoor_Activities_Hours',
       'Computer_Use_Hours', 'Watching_TV_Hours', 'Work_At_Home_Hours'],
      dtype='str')

In [8]:
data.dtypes

Region                             str
ClassGrade                       int64
Gender                             str
Ageyears                       float64
Height_cm                          str
Travel_to_School                   str
Travel_time_to_School          float64
Favourite_physical_activity        str
Allergies                          str
Vegetarian                         str
Favorite_School_Subject            str
Sleep_Hours_Schoolnight            str
Sleep_Hours_Non_Schoolnight        str
Outdoor_Activities_Hours       float64
Computer_Use_Hours             float64
Watching_TV_Hours              float64
Work_At_Home_Hours                 str
dtype: object

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Region                       501 non-null    str
 1   ClassGrade                   501 non-null    int64
 2   Gender                       498 non-null    str
 3   Ageyears                     494 non-null    float64
 4   Height_cm                    480 non-null    str
 5   Travel_to_School             480 non-null    str
 6   Travel_time_to_School        481 non-null    float64
 7   Favourite_physical_activity  446 non-null    str
 8   Allergies                    443 non-null    str
 9   Vegetarian                   445 non-null    str
 10  Favorite_School_Subject      444 non-null    str
 11  Sleep_Hours_Schoolnight      445 non-null    str
 12  Sleep_Hours_Non_Schoolnight  447 non-null    str
 13  Outdoor_Activities_Hours     431 non-null    float64
 14  Computer_Use_Hours           427 non-null    float64
 15  Watching_TV_Hours            427 non-null    float64
 16  Work_At_Home_Hours           425 non-null    str
dtypes: float64(5), int64(1), str(11)
memory usage: 66.7 KB

In [10]:
display(data)

,Region,ClassGrade,Gender,Ageyears,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
0,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
1,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
2,WI,8,Male,14.0,174,Bicycle,8.0,Baseball/Softball,Yes,No,Physical education,7,9,12.0,4.0,6.0,3
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,MD,6,Female,12.0,145,Bus,15.0,Dancing,Yes,No,Social studies,9,10,14.0,9.0,4.0,3
497,OH,12,Male,17.0,183,Car,15.0,Table Tennis,No,No,Languages,4,10,0.0,56.0,0.0,15
498,MI,11,Female,16.0,169,Car,5.0,Rowing,Yes,No,Science,6,9,5.0,15.0,20.0,10
499,TX,12,Male,17.0,162,Car,35.0,Running/Jogging,Yes,No,NaN,5,7,2.0,25.0,1.0,10
500,GA,6,Female,11.0,148,Bus,17.0,Running/Jogging,No,No,NaN,7,8,14.0,15.0,3.0,2

In [11]:
data.describe()

,ClassGrade,Ageyears,Travel_time_to_School,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours
count,501.000000,494.000000,481.000000,431.000000,427.000000,427.000000
mean,10.299401,15.732126,16.004158,8.730858,16.804450,7.487119
std,2.309584,2.661917,15.697664,13.423364,21.566521,11.272831
min,4.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,14.000000,7.000000,2.000000,4.000000,1.000000
50%,12.000000,17.000000,10.000000,5.000000,10.000000,4.000000
75%,12.000000,17.000000,20.000000,12.000000,20.000000,9.000000
max,12.000000,44.000000,187.000000,168.000000,168.000000,100.000000

In [12]:


male_data = data[data["Gender"] == "Male"]
print(male_data)

    Region  ClassGrade Gender  Ageyears Height_cm Travel_to_School  \
0       WI          12   Male       NaN       193              Car
1       WI          12   Male       NaN       193              Car
2       WI           8   Male      14.0       174          Bicycle
3       CA          12   Male      17.0        62              Car
4       IN          12   Male      17.0       179              Bus
..     ...         ...    ...       ...       ...              ...
491     VA          11   Male      16.0       178              Car
492     IN          12   Male      16.0       183              Bus
495     IN          10   Male      15.0     172.7              Bus
497     OH          12   Male      17.0       183              Car
499     TX          12   Male      17.0       162              Car

     Travel_time_to_School Favourite_physical_activity Allergies Vegetarian  \
0                     15.0                       Other       Yes         No
1                     15.0                       Other       Yes         No
2                      8.0           Baseball/Softball       Yes         No
3                      8.0                      Soccer        No         No
4                     20.0                   Athletics        No         No
..                     ...                         ...       ...        ...
491                    9.0                      Soccer        No         No
492                   60.0         Football (American)       Yes         No
495                   15.0                     Cycling        No         No
497                   15.0                Table Tennis        No         No
499                   35.0             Running/Jogging       Yes         No

        Favorite_School_Subject Sleep_Hours_Schoolnight  \
0                       Science                       6
1                       Science                       6
2            Physical education                       7
3                         Other                       8
4                Social studies                       6
..                          ...                     ...
491  Mathematics and statistics                       8
492                     History                       6
495                     Science                       9
497                   Languages                       4
499                         NaN                       5

    Sleep_Hours_Non_Schoolnight  Outdoor_Activities_Hours  Computer_Use_Hours  \
0                             9                      10.0                 3.0
1                             9                      10.0                 3.0
2                             9                      12.0                 4.0
3                            10                      15.0                 3.0
4                             9                       1.0                 3.0
..                          ...                       ...                 ...
491                          10                      17.0                11.0
492                          10                       1.0                12.0
495                          10                      14.0                14.0
497                          10                       0.0                56.0
499                           7                       2.0                25.0

     Watching_TV_Hours Work_At_Home_Hours
0                  5.0                  2
1                  5.0                  2
2                  6.0                  3
3                  0.0                 20
4                  2.0                  5
..                 ...                ...
491                7.0                 10
492                1.0                  2
495                1.0                  2
497                0.0                 15
499                1.0                 10

[251 rows x 17 columns]

In [13]:

data[data["Ageyears"].isnull()]
print(data)

    Region  ClassGrade  Gender  Ageyears Height_cm Travel_to_School  \
0       WI          12    Male       NaN       193              Car
1       WI          12    Male       NaN       193              Car
2       WI           8    Male      14.0       174          Bicycle
3       CA          12    Male      17.0        62              Car
4       IN          12    Male      17.0       179              Bus
..     ...         ...     ...       ...       ...              ...
496     MD           6  Female      12.0       145              Bus
497     OH          12    Male      17.0       183              Car
498     MI          11  Female      16.0       169              Car
499     TX          12    Male      17.0       162              Car
500     GA           6  Female      11.0       148              Bus

     Travel_time_to_School Favourite_physical_activity Allergies Vegetarian  \
0                     15.0                       Other       Yes         No
1                     15.0                       Other       Yes         No
2                      8.0           Baseball/Softball       Yes         No
3                      8.0                      Soccer        No         No
4                     20.0                   Athletics        No         No
..                     ...                         ...       ...        ...
496                   15.0                     Dancing       Yes         No
497                   15.0                Table Tennis        No         No
498                    5.0                      Rowing       Yes         No
499                   35.0             Running/Jogging       Yes         No
500                   17.0             Running/Jogging        No         No

    Favorite_School_Subject Sleep_Hours_Schoolnight  \
0                   Science                       6
1                   Science                       6
2        Physical education                       7
3                     Other                       8
4            Social studies                       6
..                      ...                     ...
496          Social studies                       9
497               Languages                       4
498                 Science                       6
499                     NaN                       5
500                     NaN                       7

    Sleep_Hours_Non_Schoolnight  Outdoor_Activities_Hours  Computer_Use_Hours  \
0                             9                      10.0                 3.0
1                             9                      10.0                 3.0
2                             9                      12.0                 4.0
3                            10                      15.0                 3.0
4                             9                       1.0                 3.0
..                          ...                       ...                 ...
496                          10                      14.0                 9.0
497                          10                       0.0                56.0
498                           9                       5.0                15.0
499                           7                       2.0                25.0
500                           8                      14.0                15.0

     Watching_TV_Hours Work_At_Home_Hours
0                  5.0                  2
1                  5.0                  2
2                  6.0                  3
3                  0.0                 20
4                  2.0                  5
..                 ...                ...
496                4.0                  3
497                0.0                 15
498               20.0                 10
499                1.0                 10
500                3.0                  2

[501 rows x 17 columns]

In [14]:
df_filled=data.fillna(9)
display(df_filled)

,Region,ClassGrade,Gender,Ageyears,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
0,WI,12,Male,9.0,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
1,WI,12,Male,9.0,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
2,WI,8,Male,14.0,174,Bicycle,8.0,Baseball/Softball,Yes,No,Physical education,7,9,12.0,4.0,6.0,3
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,MD,6,Female,12.0,145,Bus,15.0,Dancing,Yes,No,Social studies,9,10,14.0,9.0,4.0,3
497,OH,12,Male,17.0,183,Car,15.0,Table Tennis,No,No,Languages,4,10,0.0,56.0,0.0,15
498,MI,11,Female,16.0,169,Car,5.0,Rowing,Yes,No,Science,6,9,5.0,15.0,20.0,10
499,TX,12,Male,17.0,162,Car,35.0,Running/Jogging,Yes,No,9,5,7,2.0,25.0,1.0,10
500,GA,6,Female,11.0,148,Bus,17.0,Running/Jogging,No,No,9,7,8,14.0,15.0,3.0,2

In [15]:
data.duplicated()

0      False
1       True
2      False
3      False
4      False
       ...
496    False
497    False
498    False
499    False
500    False
Length: 501, dtype: bool

In [16]:
data=data.drop_duplicates()
display(data)

,Region,ClassGrade,Gender,Ageyears,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
0,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
2,WI,8,Male,14.0,174,Bicycle,8.0,Baseball/Softball,Yes,No,Physical education,7,9,12.0,4.0,6.0,3
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5
5,MO,11,Male,16.0,180,NaN,25.0,Soccer,No,No,Mathematics and statistics,7,10,1.0,3.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,MD,6,Female,12.0,145,Bus,15.0,Dancing,Yes,No,Social studies,9,10,14.0,9.0,4.0,3
497,OH,12,Male,17.0,183,Car,15.0,Table Tennis,No,No,Languages,4,10,0.0,56.0,0.0,15
498,MI,11,Female,16.0,169,Car,5.0,Rowing,Yes,No,Science,6,9,5.0,15.0,20.0,10
499,TX,12,Male,17.0,162,Car,35.0,Running/Jogging,Yes,No,NaN,5,7,2.0,25.0,1.0,10
500,GA,6,Female,11.0,148,Bus,17.0,Running/Jogging,No,No,NaN,7,8,14.0,15.0,3.0,2

In [17]:
new_data=data.rename(columns={"Ageyears":"Age"})
display(new_data)

,Region,ClassGrade,Gender,Age,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
0,WI,12,Male,NaN,193,Car,15.0,Other,Yes,No,Science,6,9,10.0,3.0,5.0,2
2,WI,8,Male,14.0,174,Bicycle,8.0,Baseball/Softball,Yes,No,Physical education,7,9,12.0,4.0,6.0,3
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5
5,MO,11,Male,16.0,180,NaN,25.0,Soccer,No,No,Mathematics and statistics,7,10,1.0,3.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,MD,6,Female,12.0,145,Bus,15.0,Dancing,Yes,No,Social studies,9,10,14.0,9.0,4.0,3
497,OH,12,Male,17.0,183,Car,15.0,Table Tennis,No,No,Languages,4,10,0.0,56.0,0.0,15
498,MI,11,Female,16.0,169,Car,5.0,Rowing,Yes,No,Science,6,9,5.0,15.0,20.0,10
499,TX,12,Male,17.0,162,Car,35.0,Running/Jogging,Yes,No,NaN,5,7,2.0,25.0,1.0,10
500,GA,6,Female,11.0,148,Bus,17.0,Running/Jogging,No,No,NaN,7,8,14.0,15.0,3.0,2

In [18]:


data[(data["Ageyears"] == 17) & (data["ClassGrade"] == 12)]

,Region,ClassGrade,Gender,Ageyears,Height_cm,Travel_to_School,Travel_time_to_School,Favourite_physical_activity,Allergies,Vegetarian,Favorite_School_Subject,Sleep_Hours_Schoolnight,Sleep_Hours_Non_Schoolnight,Outdoor_Activities_Hours,Computer_Use_Hours,Watching_TV_Hours,Work_At_Home_Hours
3,CA,12,Male,17.0,62,Car,8.0,Soccer,No,No,Other,8,10,15.0,3.0,0.0,20
4,IN,12,Male,17.0,179,Bus,20.0,Athletics,No,No,Social studies,6,9,1.0,3.0,2.0,5
7,IN,12,Female,17.0,160.2,Bus,15.0,Other,No,No,English,5,4,NaN,70.0,70.0,14
10,NY,12,Female,17.0,173,Car,10.0,Other,No,No,Science,8,12,2.0,50.0,50.0,1
11,CO,12,Female,17.0,168,Car,20.0,Baseball/Softball,No,No,Social studies,6,10,15.0,20.0,15.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,CA,12,Male,17.0,183,Car,30.0,Tennis,Yes,No,Physical education,7.5,12,12.0,20.0,15.0,2
488,TX,12,Male,17.0,182,Car,15.0,Football (American),Yes,No,Physical education,7,9,12.0,2.0,2.0,2
494,AZ,12,Female,17.0,158,Bus,45.0,Dancing,Yes,No,Science,10,13,3.0,0.0,4.0,0
497,OH,12,Male,17.0,183,Car,15.0,Table Tennis,No,No,Languages,4,10,0.0,56.0,0.0,15
499,TX,12,Male,17.0,162,Car,35.0,Running/Jogging,Yes,No,NaN,5,7,2.0,25.0,1.0,10

In [19]:
data.groupby("Region")["ClassGrade"].count()

Region
AK     2
AL     1
AR     8
AZ     7
CA    64
CO    10
CT     5
DC     5
DE     4
FL    10
GA    20
GU     3
HI     1
IA     4
ID     7
IL    12
IN    32
KS     4
KY     2
MA    18
MD    10
MI    11
MN     8
MO     7
MT     1
NC    36
NE     4
NH     2
NJ     9
NM     2
NY    19
OH    23
OK     4
OR     3
PA    22
RI     6
SC    24
SD     2
TN     6
TX    25
UT     1
VA    12
VT     4
WA     6
WI    32
WY     2
Name: ClassGrade, dtype: int64

In [20]:
data["Ageyears"].value_counts()

Ageyears
17.00    200
16.00     71
18.00     53
12.00     36
14.00     33
15.00     27
13.00     27
11.00     26
10.00      8
20.00      3
19.00      2
9.00       2
24.00      2
21.00      1
11.67      1
44.00      1
25.00      1
Name: count, dtype: int64

In [21]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Appu", "ammu", "anu"]
})

# Second DataFrame
df2 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [40, 50, 60]
})

# Merge using common column "ID"
merged_df = pd.merge(df1, df2, on="ID")

display(merged_df)

   ID  Name  Marks
0   1  Appu     40
1   2  ammu     50
2   3   anu     60